delete from users;
INSERT INTO users (id, email, password, name) VALUES
(1, 'admin@gmail.com', 'admin', 'Admin'),
(2, 'david@gmail.com', 'david', 'David'),
(3, 'ron@gmail.com', 'ron', 'Ron');
insert into posts(id, title, content, created_on, updated_on) values
(1, 'Introducing SpringBoot', 'SpringBoot is awesome', '2017-05-10', null),
(2, 'Securing Web applications', 'This post will show how to use SpringSecurity','2017-05-20', null),
(3, 'Introducing Ajax app', 'Developing social web applications using Spring Social','2017-07-21', null),
(4, 'Spring Boot Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(5, 'Writing Some App', 'Developing social web applications using Spring Social','2016-07-24', null),
(6, 'Top 10 Spring Boot App', 'Developing social web applications using Spring Social','2017-05-24', null),
(7, 'Nothing to write', 'Developing social web applications using Spring Social','2018-05-24', null),
(8, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(9, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(10, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(11, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(12, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(13, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(14, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(15, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(16, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(17, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(18, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(19, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(20, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(21, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(22, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(23, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(24, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(25, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(26, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(27, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(28, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(29, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(30, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(31, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(32, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(33, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(34, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(35, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(36, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(37, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(38, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(39, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(40, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(41, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(42, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(43, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null),
(44, 'Introducing Spring Social', 'Developing social web applications using Spring Social','2017-05-24', null);
insert into comments(id, post_id, name, email, content, created_on, updated_on) values
(1, 1, 'John','john@gmail.com', 'This is cool', '2017-05-10', null),
(2, 1, 'Rambo','rambo@gmail.com', 'Thanks for awesome tips', '2017-05-20', null),
(3, 2, 'Paul', 'paul@gmail.com', 'Nice post buddy.', '2017-05-24', null);
